### ISSUE TITLE
Dynamic threshold for pattern cleaning

### ISSUE THREAD

**Issue by jjanetzki** [jjanetzki/fact_extraction#38]
- not just > 1
- evaluate use

**Comment by dominikglandorf** [comment]
config.ini contains thresholds for words and types. A value below 1 is taken as a dynamic threshold. The type threshold cuts types with a frequency lower than the configured amount relative to the most common type. The dynamic word threshold is the lower bound for the relative total word count which should be achieved. A value of 0.8 means, that so many words will be cut off until there remain 80% of inital total words.
