### ISSUE TITLE
Some DBpedia pages have no corresponding Wikipedia pages

### ISSUE THREAD

**Issue by jjanetzki** [jjanetzki/fact_extraction#64]
e.g.
Existent: http://dbpedia.org/resource/Mobile_Suit_Gundam_Wing__manga__1
Non-existent: https://de.wikipedia.org/wiki/Mobile_Suit_Gundam_Wing__manga__1

**Comment by dominikglandorf** [comment]
__ (double underscore) is never used Wikipedia article links
