### ISSUE TITLE
Create poster for presentation

### ISSUE THREAD

**Issue by dominikglandorf** [jjanetzki/fact_extraction#67]
Examples: https://drive.google.com/drive/folders/0ByLm0gdMsX1jTWV4dXRpZ2Jpams
Size: A1
Create with vector program
Submit as PDF (<< 60MB)

**Comment by jjanetzki** [comment]
Examples: https://drive.google.com/drive/folders/0ByLm0gdMsX1jeWRIaEhua2hOUVE
